
Parameters:
  Vpc_Name:
    Description: Name of VPC
    Type: String
  PublicSubName:
    Description: Public Subnet
    Type: String
  PrivateSubName:
    Description: Private Subnet
    Type: String 
  InstanceName:
    Description: Instance Name
    Type: String
  SecGroupName:
    Description: Sec Group Name
    Type: String 
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.200.0/16"
      Tags:
        - Key: Name
          Value: !Ref Vpc_Name
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-west-2a" 
      VpcId: !Ref VPC
      CidrBlock: "192.168.150.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Ref PublicSubName
  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "us-east-2b" 
      VpcId: !Ref MyVPC
      CidrBlock: "192.168.150.1/24"
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Ref PrivateSubName
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP access"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
  
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0934876d4af885202"
      InstanceType: "t2.micro"
      KeyName: "Joseph_KeyPair"
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup
